export const CHANGE_PRODUCT_STORE = 'products/CHANGE_PRODUCT_STORE'
export const CHANGE_BULK_PRODUCT_STORE = 'products/CHANGE_BULK_PRODUCT_STORE'

// @TODO: FOR FUTURE FEATURE
export const ADD_PRODUCT = 'products/ADD_PRODUCT'
export const UPDATE_PRODUCT = 'products/UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'products/DELETE_PRODUCT'
export const FETCH_PRODUCTS_REQUEST = 'products/FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_FAILURE = 'products/FETCH_PRODUCTS_FAILURE'
export const FETCH_PRODUCTS_SUCCESS = 'products/FETCH_PRODUCTS_SUCCESS'
